---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-14.04
  driver:
    customize:
      memory: 384
      cpus: 1
    network:
      - ["private_network", {'ip': '192.168.56.5'}]
- name: ubuntu-12.04
  driver:
    customize:
      memory: 384
      cpus: 1
    network:
      - ["private_network", {'ip': '192.168.56.5'}]
- name: centos-6.5
  driver:
    customize:
      memory: 384
      cpus: 1
    network:
      - ["private_network", {'ip': '192.168.56.5'}]
- name: centos-7.0
  driver:
    customize:
      memory: 384
      cpus: 1
    network:
      - ["private_network", {'ip': '192.168.56.5'}]
- name: debian-7.6
  driver:
    customize:
      memory: 384
      cpus: 1
    network:
      - ["private_network", {'ip': '192.168.56.5'}]
- name: debian-6.0.10
  driver:
    customize:
      memory: 384
      cpus: 1
    network:
      - ["private_network", {'ip': '192.168.56.5'}]

suites:
  - name: default
    run_list: 
    - recipe[pxe]
    attributes:
