---
driver_config:
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.8

platforms:

- name: ubuntu-12-04-x64
  driver_plugin: digitalocean
  driver_config:
    image: ubuntu-12-04-x64
    size: 512mb
    region: nyc3
    ssh_key_ids: [<%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>]
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
    - recipe[chef-pxe]

suites:
  - name: default
    run_list:
    attributes:
