AlignParameters:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30